### ISSUE TITLE
Your Portfolio

### ISSUE THREAD

**Issue by Markus-bit** [pr2tik1/pr2tik1#3]
Hi, i was looking at your portfolio, really nice btw, and I noticed that I could scroll out of your portfolio. Adding "overflow: hidden;" to the body tag in your css could maybe fix this issue.

Kind regards:
Markus-bit

**Comment by pr2tik1** [comment]
Hi @Markus-bit sorry for late reply, I regularly update my portfolio, not sure if you are talking about the current one. Anyways thank you for your suggestion !
